spring:
  application:
    name: msa-auth

  datasource:
    url: jdbc:h2:mem:testdb                       # H2? ??? JDBC URL (??? ??????? ?? URL)
    driver-class-name: org.h2.Driver              # H2 ?????? ???? ???
    username: sa                                  # ?? ??? ??
    password:                                     # ?? ???? (? ?)
  jpa:
    hibernate:
      ddl-auto: update                            # "update"? ?? ?????? ?? ? ???? ???
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect  # H2 ??????? ??? Hibernate ?? ??
  h2:
    console:
      enabled: true                               # H2 ? ?? ??? (localhost:8080/h2-console)
      path: /h2-console                           # H2 ?? ?? ?? (?? ? ?? ??)
