spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

cors:
  allowed-origins: "http://localhost:3000"

jwt:
  secret-key: mysecretkeymysecretkeymysecretkey
  access-token-expiration-ms: 1200000
  refresh-token-expiration-ms: 604800000
